### ISSUE TITLE
Mails are no longer being send when using the flow builder

### ISSUE THREAD

**Issue by TimWuyts** [FriendsOfShopware/FroshPlatformTemplateMail#42]
### PHP Version

7.4

### Shopware Version

6.4.17

### Actual behaviour

Email notifications triggered using the flow builder are no longer being send. The mail action fails silently without throwing any error messages.

### Expected behaviour

Email notifications triggered using the flow builder actually being send :) 

### Steps to Reproduce?

I've already managed to isolate the issue, which seems to be related to the following...

When I put the "FlowSendMailActionEvent" in comments in "Shopware\Core\Content\Flow\Dispatching\Action\SendMailAction" the code execution will continue as expected, however this won't be triggering the "sendMail" function in "Frosh\TemplateMail\Subscriber\FlowSubscriber". It seems to go wrong with "TemplateMailBusinessEvent" going further...

**Comment by danielDigitalArt** [comment]
Dont know if it related to your bug, with shopware 6.4.17 there is a bug sending mails in flow with attachments, this was fixed in 6.4.17.1. But there was another problem where it said in the dev.log file:
```
app.ERROR: Could not execute flow with error message: Flow name: Contact form sent Flow id: 0 Typed property Shopware\Core\Content\Flow\Events\FlowSendMailActionEvent::$flow must not be accessed before initialization Error Code: 0  [] []
```

In order to see these messages, the development setting must be set in the .env file.

I hotfix would be to make this property not typed. File: vendor/shopware/core/Content/Flow/Events/FlowSendMailActionEvent.php

Change:
private ?StorableFlow $flow;

To:
private $flow;

Im not sure if this would solve your problem, at them moment my email templates are still not sent, as they are somehow still using the old configuration, because i can see another error message in the log, stating:
```
 business_events.ERROR: mail.sent.error {"source":"core","environment":"dev","additionalData":{"message":"Could not render Mail-Template with error message:\nFailed rendering string template using Twig: Key \"lastName\" for array
 ```
 This should not be here, as the mail configuration should be loaded from the template. Can you look if this is the same for you? Maybe the Plugin does not work well with the Flowbuilder yet.

**Comment by TimWuyts** [comment]
I've seen similar errors/warnings in my logs, so it could be related...

**Comment by danielDigitalArt** [comment]
Got it working for me now, i did not change the plain.twig for the contact form, which is why it was trying to render the fields i removed from the form. Although the resulting email used the html version.

So it might be worth a shot for you to simply remove the type hint in the core file i mentioned before. If it works then it is a bug in the core which is also already known, atleast kind of: 
https://forum.shopware.com/t/6-4-17-0-mailversand-ueber-flow-geht-nicht-mehr-flow-must-not-be-accessed-before-initialization/97027/3

**Comment by TimWuyts** [comment]
It's working again after updating to 6.4.17.2.
Thanks for informing me about this one!
